### ISSUE TITLE
audioserve killed by SIGSYS on Raspbian 11

### ISSUE THREAD

**Issue by uGeek** [srd424/audioserve-docker#1]
I have mounted the docker on my vps with arm64 and it works perfectly, but for Raspberry of arm64, it doesn't work.
Great job being able to have this image for arm architecture. 

Thank you very much

**Comment by srd424** [comment]
Have you got any error messages / logs that might clue me in a bit? What version of Raspbian, docker, etc?

**Comment by srd424** [comment]
(FWIW, I run on a Raspberry Pi, but I use podman, might be worth a try. I will dig mine out and double-check the latest version runs OK on it.)

**Comment by uGeek** [comment]
In the logs it appears:

```
Attaching to audioserve
audioserve exited with code 159
```

I am using docker-compose

**Comment by srd424** [comment]
Interesting - exit code 159 implies killed by signal 31, which is SIGSYS (unknown system call) on ARM. You could try passing `--privileged` to `docker run` and seeing if that helps? Syscall filtering can be problematic, particularly on ARM which IIRC uses syscalls for things like memory barriers, at least on 32 bit.

What version of Raspbian? (`lsb_release -a` should tell you.)

**Comment by srd424** [comment]
According to https://github.com/docker/compose/issues/123#issuecomment-60128963, you can enable privileged mode in docker compose like this:
```
version: "3"

services:
  audioserve:
    image: ghcr.io/srd424/audioserve-docker:v0.22.0
    restart: unless-stopped
    command: --tags /audiobooks
    privileged: true
    environment:
      - "AUDIOSERVE_SHARED_SECRET=VGM4oDS6wGKge9"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "./config:/home/audioserve/.audioserve"
      - "/path/to/Audio/Books:/audiobooks"
```
